// Generated by https://quicktype.io

import { ventas } from "@prisma/client";

export interface VentasRequest {
    data: ventas[];
    meta: Meta;
}

export interface Datum {
    id_venta:       number;
    nombres:        string;
    identificacion: string;
    correo:         string;
    whatsapp:       string;
    productos:      string;
    vendedor:       null | number;
    fecha_creado:   string;
}

export interface Meta {
    total:       number;
    lastPage:    number;
    currentPage: number;
    perPage:     number;
    prev:        number;
    next:        number;
}
